#!/usr/bin/env python3

from discord.ext import commands
import os

from modules import db

from modules.connections import database_file as database_file
from modules.connections import bot_token as bot_token

if not os.path.exists(database_file):
    db.query("CREATE TABLE config (setting, parent, value, flag)")
    db.query("CREATE TABLE admins (user_id, permissions)")
    db.query("CREATE TABLE scoretracking_tracklist (osu_id, osu_username)")
    db.query("CREATE TABLE scoretracking_channels (osu_id, channel_id, gamemode)")
    db.query("CREATE TABLE scoretracking_history (osu_id, score_id)")

initial_extensions = [
    "cogs.BotManagement",
    "cogs.ScoreTracking",
]


class Cirno(commands.Bot):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.background_tasks = []
        self.app_version = (open(".version", "r+").read()).rstrip()
        self.description = f"Cirno {self.app_version}"

        for extension in initial_extensions:
            try:
                self.load_extension(extension)
            except Exception as e:
                print(e)

    async def close(self):
        # Cancel all Task object generated by cogs.
        # This prevents any task still running due to having long sleep time.
        for task in self.background_tasks:
            task.cancel()
        
        # Run actual discord.py close.
        await super().close()

    async def on_ready(self):
        print("Logged in as")
        print(self.user.name)
        print(self.user.id)
        print("------")
        if not db.query("SELECT * FROM admins"):
            app_info = await self.application_info()
            if app_info.team:
                for team_member in app_info.team.members:
                    db.query(["INSERT INTO admins VALUES (?, ?)", [str(team_member.id), "1"]])
                    print(f"Added {team_member.name} to admin list")
            else:
                db.query(["INSERT INTO admins VALUES (?, ?)", [str(app_info.owner.id), "1"]])
                print(f"Added {app_info.owner.name} to admin list")


client = Cirno(command_prefix=",")
client.run(bot_token)
